# Run jazzy from the current directory to generate documentation

module: SwiftInstagram
module_version: 1.0.5
author: Ander Goig
github_url: https://github.com/AnderGoig/SwiftInstagram
exclude:
    - "Sources/Helpers/KeychainSwiftDistrib.swift"

swift_version: 4.0

clean: true
skip_undocumented: true

theme: fullwidth
output: docs
